import Head from "next/head";
import Button3D from "../src/components/buttons/Button3D";
import FireNavbar from "../src/components/navigation/FireNavbar";

import { useSession, signIn, signOut, getProviders } from "next-auth/react";

import Link from "next/link";

export default function Home({ providers }) {
  const { data: session } = useSession();

  console.log("sessions", session);

  return (
    <div>
      <Head>
        <title>WhiteMagic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <FireNavbar />
      </nav>

      <div className="h-screen bg-gradient-to-r from-gray-900 to-[#28313b]">
        <div className="text-center text-white pt-4 font-bold text-4xl">
          WhiteMagic
        </div>

        {!session &&
          Object.values(providers).map((provider) => (
            <Button3D
              key={provider.name}
              text={`Sign in with ${provider.name}`}
              onClick={() => signIn(provider.id)}
            />
          ))}

        {session && (
          <div className="text-center text-white">
            <p className="">Signed in as {session.user.email}</p>

            <p>
              <Link href="/profile-progress-bar">
              <span className="underline cursor-pointer">profile progress bar</span>
              </Link>
            </p>

            <Button3D text="Sign out" onClick={() => signOut()} />
          </div>
        )}
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const providers = await getProviders();
  return {
    props: { providers },
  };
}
